### ISSUE TITLE
途中まで手入力してマウスで選択すると...

### ISSUE THREAD

**Issue by nobm** [jphacks/NG_1811#9]
1. "c"と入力
2. "cat"を選択
3. "cat c"

**Comment by nobm** [comment]
1. "cat "を入力
3. "a"と入力
2. "ファイル名"を選択
3. "cat ファイル名 a"

も同様

**Comment by maitaken** [comment]
2番目のケースの場合って、
ファイル名の中にaが入った状態になってほしい？

**Comment by nobm** [comment]
ユーザの動線的にそうでないでしょうか（その状態にならないのであればファイル名を候補として出すべきでない）

**Comment by maitaken** [comment]
対応したのでチェックをお願いします

**Comment by nobm** [comment]
素晴らしいですねぇ
